### ISSUE TITLE
Adding upper part bonus?

### ISSUE THREAD

**Issue by space-egret** [lrvideckis/yahtzee-max-expected-score#3]
I'm looking for a piece of code that I can modify to compute scores for a Yahtzee variant using 12-sided dice. This code looks promising and is working well, except for the bonus in the upper part. Do you know how the bonus can be added to the expected values?

**Comment by lrvideckis** [comment]
Hey! I guess time to revisit this after 2 years haha.

So I think I have an approach: we have to modify the DP state to 

double maxEV[1<<13][3][252][64]; // ~4e8 memory?!? - hopefully it's okay

where this new dimension represents how many points of the top section we have so far.

Then the moment this value becomes >= 63, we'll add an extra 35 points in the transition, so the new transition looks something like:

const double nextScore = scoreForRoll[roll][scoreVal] + averageMaxEV[subsetFilled ^ (1<<scoreVal)][prevFirstSectionScore] + (35 * (prevFirstSectionScore < 63 && prevFirstSectionScore + scoreForRoll[roll][scoreVal] >= 63));


https://github.com/lrvideckis/yahtzee-max-expected-score/blob/main/yahtzee.cpp#L265

**Comment by lrvideckis** [comment]
I'll try to code it sometime this week

**Comment by lrvideckis** [comment]
probably the time to calculate the DP table will be 64x slower

**Comment by lrvideckis** [comment]
also not sure how much knowledge you have about DP=dynamic programming, for example what I mean by state,transition=recurrence, but here's a good resource

https://codeforces.com/blog/entry/80064

**Comment by lrvideckis** [comment]
Alright the code is twice as slow now as I removed some optimization which I don't fully remember how it works

But it should be a bit more clean

Now I remember how most of it works, I'll attempt to code the 35 point bonus in a bit

**Comment by space-egret** [comment]
Awesome, thanks for diving into this. My knowledge of dynamic programming and C++ is pretty limited. I learned regular C about 20 years ago, but have been using Python almost exclusively for the last 10 years. I think I can read C++ well enough to adapt the code to my made-up 12-sided Yahtzee variety, but I couldn't figure out how to add the 35-point bonus to the expectation values.
If the code will be 64x slower (on top of the factor 2), it'll take 5-10 minutes to calculate the whole table. Is there a simple way to store the table for future use, so it only has to be computed once?

**Comment by lrvideckis** [comment]
hmm good idea for saving the array

https://stackoverflow.com/a/63947433

so I'll split it up into 2 programs: one to calculate the DP table and save it to file, another to read the file and do IO

**Comment by lrvideckis** [comment]
alright a git clone just took me 1m46s with my 15mb / s  internet

**Comment by lrvideckis** [comment]
working on the IO now

**Comment by lrvideckis** [comment]
ok, just ran it a few times, and when comparing to http://www-set.win.tue.nl/~wstomv/misc/yahtzee/osyp.php, it seems to give expected values which are consistently 2-3 points less than that website

(to be explained by me not implementing the extra yahtzees)

**Comment by space-egret** [comment]
Thank you so much! It was a bit of a struggle to compile the new code on my Mac, but got it to work in the end.

**Comment by lrvideckis** [comment]
oh shoot, what error were you getting? and what was the fix? (just curious) 

fwiw I compile with gcc on linux

**Comment by space-egret** [comment]
gcc on Mac by default calls clang, which worked fine on the original code, but generated this error for the new code:

`invalid operands to binary expression ('const Transition' and 'const Transition')`
`    bool operator()(const _T1& __x, const _T1& __y) const {return __x < __y;}`
`                                                                  ~~~ ^ ~~~`

First part of the fix was to install the actual gcc from Homebrew, then update the Xcode developer tools to get the correct header files. I had to update the run.sh script to this:
g++-13 -std=c++17 -I /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include -O2 read_table_and_IO.cpp -o read_table_and_IO.out
